name: Reproduces error

on:
  workflow_dispatch:
  pull_request:
  push:


permissions:
  contents: read

jobs:
  basicTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: CD
        run: cd stage3

      - name: Run wasmJS
        run: ./gradlew wasmJsBrowserRun
