name: Reproduces error

on:
  workflow_dispatch:
  pull_request:
  push:


permissions:
  contents: read

jobs:
  basicTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run wasmJS
        run: |
          cd stage3/nine-mens-morris-app-kmp/
          ./gradlew wasmJsBrowserRun
