name: Reproduces error

on:
  workflow_dispatch:
  pull_request:
  push:


permissions:
  contents: read

jobs:
  basicTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: CD
        run: cd stage3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run wasmJS
        run: ./gradlew wasmJsBrowserRun
